### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by lolmaus** [indexiatech/ember-components#58]
Hi!

Simply installing Ember Components into my Ember CLI project via `npm install --save-dev ember-cli-components` results in the following error:

> Uncaught ReferenceError: define is not defined
> application.js:1 (anonymous function)

During the installation, i have a Bower dependency conflict:

>    1) handlebars#>= 1.0.0 < 2.0.0 which resolved to 1.3.0 and is required by ember#1.7.1 
>    2) handlebars#>= 2.0.0 < 3.0.0 which resolved to 2.0.0 and is required by ember#1.9.1

I choose `1` because i use Ember 1.8.1. I don't know where the Ember 1.9.1 dependency is coming from.

**Comment by asaf** [comment]
Hello,

Please dont install the whole package,
This project is just an umbrella for all our addons (look at the readme file)

You have an addon now per component!


Thanks

**Comment by hglattergotz** [comment]
@asaf Thanks for the hint. Just happened to me too because I read this http://indexiatech.github.io/ember-components/#/getstarted

**Comment by lolmaus** [comment]
> @asaf 
> Please dont install the whole package,
> This project is just an umbrella for all our addons (look at the readme file)

> http://indexiatech.github.io/ember-components/#/getstarted
> Install the components addon
>     npm install --save-dev ember-cli-components

Shouldn't you change the obviously misleading docs before closing this issue?

**Comment by asaf** [comment]
@lolmaus @hglattergotz Sure, I'll wipe it soon and put links to the separated components instead,

Thanks! :)
